name = "Judo"
uuid = "4ff32cee-1a95-4b6f-aa6c-81a2608e045c"
authors = ["Fang Liu <fangliu@tju.edu.cn> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
